discord:
  token: ${DISCORD_TOKEN}

open-ai:
  api:
    url: https://api.openai.com/v1/
    token: ${OPEN_AI_TOKEN}

management:
  endpoint:
    prometheus:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics" ]
