version: '3.9'
services:

  bot:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file: ../.env
    container_name: gpt-bot
    restart: always
    ports:
      - '8080:8080'
  
  prometheus:
    image: prom/prometheus:v2.42.0
    network_mode: host
    container_name: prometheus
    volumes:
      - ../src/main/resources/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana-oss:9.4.2
    user: "$UID:$GID"
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost