name: Create Release

on:
  push:
    branches:
      - release/**

env:
  COMMIT_TEXT: "${{ github.event.head_commit.message }}"

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Validate version
        run: python check_version.py

      - name: Set Tag Output
        id: set-tag
        run:  echo "::set-output name=tag_name::$(python get_version.py)"

      - name: Create Tag
        uses: actions/github-script@v3
        env:
          TAG: ${{ steps.set-tag.outputs.tag_name }}
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
             ref: "refs/tags/${{ steps.set-tag.outputs.tag_name }}",
              sha: context.sha
            })

      - name: Update version in files
        run: python update_version.py
      
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Update version to ${{ steps.set-tag.outputs.tag_name }}"

      - name: Create Release notes file
        run: python create_release_notes.py

      - name: Create Release on GitHub
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ steps.set-tag.outputs.tag_name }}
          bodyFile: './release_notes.txt'
          token: ${{ github.token }}